- integrations/opsweekly/alerta.php
> Alerta API v4 now supports to-date param

- integrations/mailer/README.md
- integrations/mailer/mailer.py
The new option skip_mta can be used to send emails directly without
using an intermediary MTA. Note this might get you black-listed and
it doesn't work in many other cases, however is quite useful to not
require any kind of email account to send notifications.
Anyone using this option may also want to use also the new
option mail_localhost to avoid getting black-listed by software like
spamhaus/cbl that might block hosts sending email using 'localhost'
as the host during the smtp EHLO command.
A few additional fixes in this commit:
* Add smtp_starttls option to enable/disable the STARTTLS extension.
This is enabled by default for security and backwards compatibility.
* Provide the endpoint and key options to ApiClient(), they were being
ignored before.
* Use adequate data types for the …
> Make the alerta mailer use of an MTA optional

- integrations/mailer/mailer.py
Sorry, I missed this when making a simple last minute change to my MTA pull request and I didn't install that one change when testing so turns out that small change broke the mailer startup. This fixes the startup issue.
> Add missing global declaration

- integrations/mailer/README.md
- integrations/mailer/mailer.py
The template location can now be specified using the configuration option 'mail_template'
The subject can be specified using a jinja string/template using 'mail_subject', defaulting to the same string as before.
I added a small fix on the logging configuration that strictly speaking has nothing to do with this PR but seemed like overkill to make another PR for a simple one-liner. If you prefer a separate PR just let me know.
> Make the mailer template location and the mail subject configurable

- integrations/mailer/README.md
- integrations/mailer/mailer.py
- integrations/mailer/setup.py
One of these changes break compatibility with the 3.2.0 version (last week released), since is not using anymore the notifications section, instead now is getting all the sections named "notification:" and iterate over them.
> Add support for multiple config files, and refactor of the notifications

- plugins/pagerduty/pagerduty.py
This PR allows the pagerduty plugin to resolve incidents automatically once an alert transitions into the "ok" state.
Based on a "resolve" event. More info in here: https://developer.pagerduty.com/documentation/integration/events/resolve
> Pagerduty: automatically resolve incidents when alert severity is "ok" 

- integrations/mailer/README.md
- integrations/mailer/mailer.py
- integrations/mailer/setup.py
@jmesquita pointed a concern that I admit with lot of shame that I've used eval and not getattr I am sorry for this, the PR is attached
> Changing eval for getattr because security reasons, spotted by @jmesquita

- integrations/mailer/README.md
- integrations/mailer/mailer.py
- integrations/mailer/setup.cfg
- integrations/mailer/setup.py
- integrations/mailer/tests/test_rules.py
* alerta-mailer now has unit tests using py.test
* rules should be ported to new JSON format
The reasoning behind this is to make use of a more machine friendly format to email rules without compromising human readability. Using a nested format like JSON allows us to provide more flexibility to the configuration as well.
Another PR based on this PR is coming to extend functionality but I wanted to split it in two parts so we can have better review process on the modifications.
> Move email rules to more flexible JSON format

- plugins/slack/setup.py
- plugins/slack/slack.py
Service field in a Slack message is empty:
While the json data sent to Alerta actually includes a service attribute:
According to the document (http://docs.alerta.io/en/latest/api/reference.html#send-an-alert), the "service" attribute is sent to Alerta in an array of string:
```
{
"resource": "web01",
"event": "HttpServerError",
"environment": "Production",
"severity": "major",
"status": "open",
"correlate": [
"HttpServerError",
"HttpServerOK"
],
"service": [
"example.com"
],
"group": "Web",
"value": "Bad Gateway (501)",
"text": "The site is down.",
"tags": [
"london"
],
"attributes": {
"company": "ACME Corp"
},
"origin": "curl",
"type": "webAlert"
}
```
So it makes sense to join these strings with `", "` for displaying message purpose.
> Fix empty service field when posting to slack

- plugins/amqp/alerta_amqp.py
- plugins/amqp/setup.py
- plugins/enhance/alerta_enhance.py
- plugins/enhance/setup.py
- plugins/geoip/alerta_geoip.py
- plugins/geoip/setup.py
- plugins/hipchat/alerta_hipchat.py
- plugins/hipchat/setup.py
- plugins/influxdb/alerta_influxdb.py
- plugins/influxdb/setup.py
- plugins/logstash/alerta_logstash.py
- plugins/logstash/setup.py
- plugins/normalise/alerta_normalise.py
- plugins/normalise/setup.py
- plugins/pagerduty/alerta_pagerduty.py
- plugins/pagerduty/setup.py
- plugins/prometheus/alerta_prometheus.py
- plugins/prometheus/setup.py
- plugins/pushover/alerta_pushover.py
- plugins/pushover/setup.py
- plugins/slack/setup.py
- plugins/slack/slack.py
- plugins/sns/alerta_sns.py
- plugins/sns/setup.py
- plugins/syslog/alerta_logger.py
- plugins/syslog/setup.py
- plugins/twilio/alerta_twilio_sms.py
- plugins/twilio/setup.py
Example
```
2016-09-15 10:13:43,960 - alerta.plugins.geoip[11818]: CRITICAL - this is from GEO IP !!!!!! [in build/bdist.macosx-10.9-x86_64/egg/alerta_geoip.py:18]
```
> Set useful logger name for plugins

- integrations/mailer/mailer.py
In order to be compatible with multiple languages, the text(the subject included) in the message body should be encoded in utf-8 to avoid `UnicodeEncodeError`when we call msg.as_string(). It seems that the subject field in line 279 misses it, I fixed it with `Header` wrapper.
> Fix codec error if the text includes non-ascii charators

- plugins/prometheus/README.md
- plugins/prometheus/alerta_prometheus.py
- plugins/prometheus/setup.py
Remove silences created by Alerta from Prometheus Alertmanager when an alert is manually set to `open`. Note that this takes advantage of an undocumented API.
Fixes guardian/alerta#278
> Delete silences in Prometheus Alertmanager

- plugins/slack/alerta_slack.py
- plugins/slack/setup.py
The Slack plugin was broken since last commit when ALERTA_UI_URL was removed.
My guess was that the intention was to use DASHBOARD_URL instead, which I have replaced in this pull request.
I have tested the plugin and can confirm that it successfully works with this pull request
> Fix Slack Plugin

- integrations/snmptrap/README.md
- integrations/snmptrap/handler.py
```json
"alert": {
"attributes": {
"trapvars": {
"_#": "3",
"_1": "0:1:41:43.19",
"_2": "iso.3.6.1.6.3.1.1.5.3.0",
"_3": "\"This is a test linkDown trap\"",
"_A": "0.0.0.0",
"_B": "localhost",
"_N": ".",
"_O": "iso.3.6.1.6.3.1.1.5.3.0",
"_P": "TRAP2, SNMP v2c, community public",
"_T": "0",
"_W": "Enterprise Specific",
"_X": "15:05:45",
"_a": "0.0.0.0",
"_b": "UDP: [127.0.0.1]:48476->[127.0.0.1]:162",
"_q": "0",
"_s": "SNMPv2c",
"_t": "1482073545",
"_w": "6",
"_x": "2016-12-18"
}
},
...
```
> Add snmp trapvars to alert attributes

- integrations/mailer/mailer.py
As per python docs os.uname is only available on Unix like systems,
should be plaform.uname for cross compatibility.
https://docs.python.org/dev/library/os.html#os.uname
> Fix cross platform compatiblity for windows

- plugins/influxdb/alerta_influxdb.py
We wanted to record severity as a tag in InfluxDB when using this plugin.  I've added it as a single line where other tags are defined.
> record alert severity in influxdb as a tag

- AUTHORS
- LICENSE
- README.md
- integrations/mailer/README.md
- integrations/snmptrap/setup.py
- integrations/sqs/setup.py
- integrations/syslog/setup.py
- integrations/urlmon/setup.py
- plugins/amqp/setup.py
- plugins/cachet/setup.py
- plugins/enhance/setup.py
- plugins/geoip/setup.py
- plugins/hipchat/setup.py
- plugins/influxdb/setup.py
- plugins/logstash/setup.py
- plugins/normalise/setup.py
- plugins/pagerduty/setup.py
- plugins/prometheus/setup.py
- plugins/pubsub/setup.py
- plugins/sns/setup.py
- plugins/twilio/setup.py
All the README files referred to using the MIT license but some python setup.py actually listed the Apache 2 license. This change makes sure everything is MIT license and that all current contrib AUTHORS are acknowledged.
> Make everything MIT license

- plugins/influxdb/alerta_influxdb.py
- plugins/influxdb/setup.py
I wanted to provide an option to output to a single InfluxDB measurement rather than one per event
The default behavior is to create one measurement per alert.event in InfluxDB.  Some uses of InfluxDB are easier if all Alerta data is available in a single measurement with a tag that indicates alert.event.
This introduces two new config variables:
INFLUXDB_SEPARATE_MEASUREMENT defaults to True and triggers the default (separate measurement per event) behavior.
INFLUXDB_SINGLE_MEASUREMENT defaults to False and triggers the new behavior of one measurement for all events.  If set it should be set to the name of the measurement you want to use (e.g. not True but rather "alert_measurement").
Both behaviors can be either enabled or disabled (i.e. it isn't one or the other behavior...you can have …
> Allow InfluxDB plugin to use a single measurement

- plugins/slack/README.md
- plugins/slack/alerta_slack.py
By adding a new optionnal setting, it is now possible to setup some dedicated slack channels for posting channels.
> Add support for per environment alert channel

- plugins/opsgenie/alerta_opsgenie.py
This was an "oops" on a refactoring; the result of the post should have been returned, not the alert
> Fix refactoring typo

- plugins/hipchat/README.md
- plugins/hipchat/alerta_hipchat.py
- plugins/hipchat/setup.py
Added a couple of extra config options to allow use of privately hosted Hipchat instances:
- HIPCHAT_URL (seems obvious)
- HIPCHAT_VERIFY_SSL - allow disable of Python's SSL verification in case of self-signed or internal SSL certs
> Enable use of internally hosted Hipchat instances

- plugins/slack/alerta_slack.py
- plugins/slack/setup.py
This PR adds support for the followings:
* optionally send a slack notification when an alert transitions to ack. The behavior is driven by the SLACK_SEND_ON_ACK boolean variable.
* optionally override the default severities map via SLACK_SEVERITY_MAP. The behavior is actually a merge between the defaults (SLACK_DEFAULT_SEVERITY_MAP) and the user-defined dictionary.
> Slack message upon ack and override severity maps

- plugins/influxdb/alerta_influxdb.py
- plugins/influxdb/setup.py
I've made the following changes to the InfluxDB plugin:
* add the alert tags in the format of `k=v` to the InfluxDB metric point as tags
* retain metric point value type if it's a digit (float, int)
* add status as a tag to InfluxDB metric point
* send alert status changes to InfluxDB (ack and assign). Add `text` as an optional field.
> InfluxDB plugin improvements

- plugins/amqp/alerta_amqp.py
- plugins/amqp/setup.py
After upgrading to alerta-server to 5.x, `alerta-mailer` produced the following error:
```
WARNING:mailer:dates must be ISO 8601 date format YYYY-MM-DDThh:mm:ss.sssZ
dates must be ISO 8601 date format YYYY-MM-DDThh:mm:ss.sssZ
```
Issue seems to appear during alert serialization in amqp plugin. Alert fields that contain datetime objects don't serialize as expected  -due to missing tzinfo- and produce date strings with missing 'Z'. 
_Avoided to implement the fix centrally (e.g. in `alerta models alert.serialize`)_ 
The following refactoring in amqp plugin resolves the issue:
- After alert serialization (in ver 5.x) update body's datetime related fields with utc-aware values
> Publish utc-aware datetimes in AMQP plugin

- plugins/pushover/alerta_pushover.py
At some stage, the `Alert` class had a `get_date()` method but it doesn't seem to anymore.
> Replace alert.get_date() with alert.create_time

- plugins/zabbix/alerta_zabbix.py
- plugins/zabbix/setup.py
Zabbix plugin will try login even if not zabbixAlert,
return directly if not zabbixAlert.
> fix bug: return directly if not zabbixAlert to avoid zabbix login error

- plugins/logstash/alerta_logstash.py
If LOGSTASH_PORT is accessed through an env variable, force it to be an integer, or else the socket connection will fail as it will be a string.
Fix a part of #184
> Convert LOGSTASH_PORT to an integer

- integrations/mailer/email.html.tmpl
- integrations/mailer/email.tmpl
The itermitems doesn't exist anymore in Python 3, so the templating fail.
items exists in both Py2 and Py3, they are a little different :
- in py3, items works as iteritems, using an iterator
- in py2, items use a copy of the list of items (it's a little less performant, but considerating the use case, it is not really important)
> the dict.iteritems doesn't exist anymore in py3.

- integrations/mailer/mailer.py
- integrations/mailer/setup.py
The mailer code doesn't deal well with multiple config files.
That should fix it.
> Fix parsing multiple config files in alerta-mail (mailer.py).

- plugins/slack/README.md
- plugins/slack/alerta_slack.py
Allows the use of "channel" when posting to slack.  As of some time ago, the Webhook API stopped supporting setting channel, and instead solely relied on the associated channel established during app install.
> Add support for Slack "Apps" API instead of Webhook API

- plugins/slack/README.md
- plugins/slack/alerta_slack.py
- Use SLACK_SUMMARY_FMT to use a templatized alert text
- Allow the slack message attachment sizes to be tuned from short True|False for readability
Note: we have completely moved off Hipchat to Slack and these were the last bits I needed to do in order to make everyone happy with the transition.
Thanks again for Alerta!
> Port jinja2 template from hipchat plugin to slack:

- plugins/prometheus/README.md
- plugins/prometheus/alerta_prometheus.py
- plugins/prometheus/setup.py
**Example BasicAuth HTTP Request**
```
POST /api/v1/silences HTTP/1.1
Host: localhost:8900
User-Agent: python-requests/2.19.1
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 233
Content-Type: application/json
Authorization: Basic cHJvbXVzZXI6cHJvbXBhc3M=
{"matchers": [{"name": "alertname", "value": "Bad"}, {"name": "instance", "value": "web02"}], "startsAt": "2018-09-11T08:08:36.000Z", "endsAt": "2018-09-12T08:08:36.000Z", "createdBy": "alerta", "comment": "status changed using CLI"}
```
Fixes #210
> Add support for BasicAuth to prometheus plugin

- plugins/twilio/alerta_twilio_sms.py
- plugins/twilio/setup.py
Python SDK has changed https://www.twilio.com/docs/libraries/python/usage-guide
Add support for multiple `TWILIO_TO_NUMBER` phone numbers (comma-separated)
**Example Twilio Plugin config**
```
PLUGINS=['twilio_sms']
TWILIO_ACCOUNT_SID='ACc1fba4719fd31c0e2a691xxxxxxxxx'
TWILIO_AUTH_TOKEN='4acd5e1ecde61ca0fbf11cexxxxxxxxxx'
TWILIO_FROM_NUMBER='+44123456789'
TWILIO_TO_NUMBER='+46987654321,+61324354657'
```
Fixes #155
> Update Twilio plugin and support multiple destinations

- integrations/mailer/mailer.py
When having multiple instances of alerta-mailer, by default each instance will create it's own queue in AMQP. 
There might be cases when you want to make multiple alerta-mailers run simultaneously and consume one queue - this is configured via 
```
amqp_queue_name = ''
amqp_queue_exclusive = False
```
directives in configuration.
> Make AMQP queue options configurable

- plugins/opsgenie/alerta_opsgenie.py
Fix usage of `Log.debug` in Opsgenie Plugin `plugins/opsgenie/alerta_opsgenie.py`. Running the plugin error messages occur complaining about not enough arguments for formatter.
> Fix Debug Log in Opsgenie Plugin

- plugins/opsgenie/alerta_opsgenie.py
Update _teams_ attribute in Opsgenie Alert Payload in accordance with the [new API](https://docs.opsgenie.com/docs/alert-api#section-create-alert). 
The [migration guide](https://docs.opsgenie.com/docs/migration-guide-for-alert-rest-api#section-4-responders-field) for old API suggests in **Responders Section**
```responders field is introduced to Create Alerts instead of recipients and teams fields. Teams, users, escalations and schedules that you want to route the alert can be identified with IDs or names of them, and type key is mandatory for each.```
List of Changes:
* Taking OPSGENIE_TEAMS (string containing comma separated list of teams) as a environment variable 
* change **teams** key in payload to **responders** (acc. to new API)
* add a new function to convert the …
> Fix Opsgenie Alert Payload: teams attribute

- plugins/msteams/alerta_msteams.py
Otherwise custom MS_TEAMS_SUMMARY_FMT fails with UnboundLocalError: local variable 'url'
referenced before assignment.
> msteams: Move url assignment out of else.

- plugins/msteams/README.md
- plugins/msteams/alerta_msteams.py
- plugins/msteams/setup.py
Add MS_TEAMS_TEXT_FMT Jinja2 template (string or file) that customizes msTeamsMessage.text(alert.text) formatting. Defaults to no formatting.
> msteams: MS_TEAMS_TEXT_FMT template

- plugins/msteams/alerta_msteams.py
- plugins/msteams/setup.py
Allows configuring/mapping severities to colors with MS_TEAMS_COLORS_MAP.
NOTE: Second commit(4cc0b3e) changes default 'warning' color from red to blue (original 'warning' color is too close to 'critical' red).
> Msteams colors MS_TEAMS_COLORS_MAP config option

- plugins/prometheus/README.md
- plugins/prometheus/alerta_prometheus.py
I can set custom ack timeout via Alerta API (from slack bot, for example), but Alerta not put this timeout to the Alertmanager, which is strange and not intuitive. 
I added new option `ALERTMANAGER_SILENCE_FROM_ACK` to allow timeout inheritance. By default it set to `False`, to follow the backward compatibility.
> Allow inheritance of ack timeout for alertmanager

- plugins/amqp/alerta_amqp.py
Using the alerta mailer integration, I found out that alerts with a very long history would block (without any errors thrown) the mailer FanoutConsumer worker (new messages are not received anymore).
This option allows to configure the AMQP plugin to not forward the alert history in the message queue, which has solved the problem for me (and alerta mailer does not make use of the history).
This PR introduces a new AMQP_SEND_ALERT_HISTORY parameter, which is True by default, so it doesn't change the default behaviour of the plugin.
> Add an option to not send the alert history in AMQP

- integrations/mailer/mailer.py
This PR allow the alerta mailer integration to exit cleanly if the SIGTERM signal is received.
This is useful when alerta-mailer is dockerized, because when stopping the container docker will send a SIGTERM signal to the process, and wait 10 seconds before killing it (which means 10 seconds delay + no clean exit if the signal is not handled by the process).
> [mailer] Add SIGTERM signal handling (useful when used in Docker).

- integrations/mailer/mailer.py
Playing with mailer, I wanted to not sending mail by default (except for rule that explicitly ask for it), and ended up unsetting the mail_to config parameter.
I found out that alerta mailer would still try to send a email, and contact the SMTP server, which ended rejecting the email because of an invalid recipient. This loose time (building the email) and resources (contacting the SMTP server etc.).
This patch will verify, after the contacts list is evaluated (depending on all rules) and check that the contacts list is not empty (discarding any empty recipient) before processing the email creation and sending.
> [mailer] Do not try to send an email to no recipient (empty contacts list)

- plugins/msteams/README.md
- plugins/msteams/alerta_msteams.py
- plugins/msteams/example-payload.json.j2
- plugins/msteams/setup.py
Few commits to prepare for msteams webhook. These commits add MS_TEAMS_PAYLOAD that allows to fully customize the http POST json payload (this is similar to SLACK_PAYLOAD). pymsteams or requests.post timeout is set to MS_TEAMS_DEFAULT_TIMEOUT (7s) instead of the default pymsteams default 60s.
Question on naming msteams webhook: I tried to use webhooks/msteams/alerta_msteams.py for teams webhook, but I assume this conflicts with plugins/msteams ? When I renamed the webhook to webhooks/msteamswebhook/alerta_msteamswebhook.py it loads. What's the recommened way for naming webhooks ?
> Msteams MS_TEAMS_PAYLOAD

- plugins/slack/README.md
- plugins/slack/alerta_slack.py
- plugins/slack/setup.py
This PR adds 2 new env variables/config to override slack channel on a per event or per severity basis.
The env variable / config are called `SLACK_CHANNEL_EVENT_MAP` and `SLACK_CHANNEL_SEVERITY_MAP` (to match the existing `SLACK_CHANNEL_ENV_MAP`)
> slack: Choose a channel based on severity or event

- webhooks/sentry/README.md
- webhooks/sentry/alerta_sentry.py
- webhooks/sentry/test_sentry.py
Add support for Sentry version 9 callbacks (alerta#281)
I had to also add my patch from #305 in order to have it working and tested correctly.
Here are some pictures of an alert sent from Sentry 9.1.2.
> Add Sentry version 9 webhook support

- plugins/prometheus/alerta_prometheus.py
Alertmanager Api may respond with empty set of silenceIds, which may cause exception
"alerta.exceptions.ApiError: Alertmanager: ERROR - list indices must
be integers or slices, not str"
This error is seen from the client, and the Alert can not be ACK-ed
> plugin/alerta-prometheus: fix 500 error when response is not as expected

- plugins/amqp/alerta_amqp.py
I found out that my previous PR was wrong when handling the boolean parameter from environment variable.
os.environ.get('AMQP_SEND_ALERT_HISTORY') will always return a string if defined, so code like :
AMQP_SEND_ALERT_HISTORY = os.environ.get('AMQP_SEND_ALERT_HISTORY') or app.config.get('AMQP_SEND_ALERT_HISTORY', DEFAULT_AMQP_SEND_ALERT_HISTORY) 
would end with AMQP_SEND_ALERT_HISTORY="True" or "False" if the env variable is defined.
So depending on how code is using it, it would not work as expected (in AMQP plugin case, the test to keep the history in the alert would always keep the history, whatever value was set in the env variable, because the final evaluated code is `if not history: history = []`.
This PR will ensure that AMQP_SEND_ALERT_HISTORY is treated as boolean when passed as …
> Fix boolean env variable

- plugins/slack/README.md
- plugins/slack/alerta_slack.py
Adds configuration setting SLACK_SEVERITY_FILTER (list) in alertad.conf to allow filtering of alerts to be forwarded to Slack based upon their severity.  For example, if `SLACK_SEVERITY_FILTER = ['warning']`, all alerts with 'warning' severity will NOT get processed or filtered by the other rules in the config file.  Alerts of any other severity will pass through this filter.
I found this useful because we use the Alerta UI as well as Slack, where we only want to get Slack notifications for the more serious stuff that requires immediate attention (severity levels of 'major' or 'critical'), and we leave it to our admin staff to look at the UI panel regularly to deal with less urgent lower level alerts.
> SLACK_SEVERITY_FILTER allows pre-filtering of alerts sent to Slack solely by severity

- plugins/slack/README.md
- plugins/slack/alerta_slack.py
- requirements-dev.txt
Because I wanted to make the general-purpose `#alerts` channel on Slack only receive important production alerts, I needed a way to be able to choose which channel an alert goes to based on environment _and_ severity.
In the process, I cleaned up the payload code a little bit and made `ICON_EMOJI` optional. Now you can upload a custom avatar for your webhook and it'll display as long as `ICON_EMOJI` isn't set.
> add SLACK_CHANNEL_MAP for environment and severity mapping

- plugins/slack/alerta_slack.py
This PR avoids a slack message for recoveries if the alert itself was included in SLACK_SEVERITY_FILTER
> Slack: Don't send recovery message if alert was not posted 

- webhooks/msteams/alerta_msteamswebhook.py
msteams(webhook): set alert status from action, not directly (issue #332)
> msteams(webhook): set alert status from action, not directly (issue #332)

- plugins/opsgenie/README.md
- plugins/opsgenie/alerta_opsgenie.py
- plugins/opsgenie/setup.py
There is currently a bug that this also addresses, which is that any status outside of `ack`, `assign` or `closed` would still cause the alert to be closed. 
This now allows for capturing ack'ing of alerts from Alerta -> OpsGenie along with keeping the current capability of closing.
In addition there is the ability to not send along alerts that are `Informational` or `Warning` within Alerta. This can be used to not send alerts to OpsGenie but allow them to still show up on the dashboard.
> Adding acking to OpsGenie

- plugins/pubsub/README.md
- plugins/pubsub/alerta_pubsub.py
- plugins/pubsub/setup.py
Update verion of pubsub plugin.
Works with never version of google  python modules.
Behavior has changed a bit - the use case behind this, is using the service to generate an audit trail of alerts.
> Update to work with later version of pubsub

- integrations/mailer/mailer.py
According to the documentation, if multiple fields are defined, they
must all match in order to send an email.
> mailer: Fix checking multiple fields.

- plugins/prometheus/alerta_prometheus.py
Change the condition line 130 tu use the declared variable  'ALERTMANAGER_USE_EXTERNALURL_FOR_SILENCES'.
It resolves issue 'USE_AM_EXTERNALURL_FOR_SILENCES' is not defined : https://github.com/alerta/alerta-contrib/issues/379
> fix : issue #379

- requirements-dev.txt
fix tests
**Description**
A clear and concise description of **why** this change is necessary.
Fixes # (issue)
**Changes**
Include a brief summary of changes...
- change 1
- change 2
- change 3
**Screenshots**
If it's a UI change add screenshots to demonstrate changes.
**Checklist**
**Collaboration**
When a user creates a pull request from a fork that they own, the user
generally has the authority to decide if other users can commit to the
pull request's compare branch. If the pull request author wants greater
collaboration, they can grant maintainers of the upstream repository
(that is, anyone with push access to the upstream repository) permission
to commit to the pull request's compare branch
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-fork …
> add StrEnum package
