integrations/opsweekly/README.md
integrations/opsweekly/alerta.php
integrations/opsweekly/test.php

Opsweekly integration

---

plugins/twilio/twilio_sms.py

Use env vars to config twilio sms plugin

---

integrations/mailer/README.md
integrations/mailer/mailer.py
integrations/mailer/setup.py

With this PR the idea is to add more customization based on applying regular expressions on some fields and if some of these regexp matches it will send an email to other recipients

Add notifications feature for more customized options for mails.

---

integrations/mailer/README.md
integrations/mailer/mailer.py
integrations/mailer/setup.cfg
integrations/mailer/setup.py
integrations/mailer/tests/test_rules.py

Regexes on this are now applied to items on a list as well as a string

Allow for matching rules to other types

---

plugins/slack/README.md
plugins/slack/setup.py
plugins/slack/slack.py

Fix slack attachment config var and add README

---

plugins/slack/setup.py
plugins/slack/slack.py

Make slack channel and alerta ui url configurable

Add SLACK_CHANNEL and ALERTA_UI_URL vars

---

integrations/mailer/mailer.py
integrations/mailer/tests/test_rules.py

This bug was introduced during the json routing rules refactoring.
The global OPTIONS['mail_to'] setting was being modified instead of
using a copy causing every new alert notification to start with the
notification list from the previous notification instead of the
original global settings.
I've also updated the tests to be more resilient to internal
implementation changes and focus on testing the input/output of
the send_email() function. The function now returns the email
message sent and the list of contacts on success or None on failure.

Fix alerta mailer routing bug causing mails to be sent to everyone

---

integrations/supervisor/evlistener.py

Fix supervisor resource to make it unique by host

---

integrations/syslog/setup.py
integrations/syslog/syslogfwder.py

```
{
"correlate": [
"UserEmerg",
"UserAlert",
"UserCrit",
"UserErr",
"UserWarning",
"UserNotice",
"UserInfo",
"UserDebug"
],
"event": "UserNotice",
...
}
```

Correlate syslog alerts for same facility

---

plugins/syslog/README.md
plugins/syslog/logger.py
plugins/syslog/setup.py

Add plugin for logging alerts to syslog

---

plugins/amqp/amqp.py
plugins/amqp/setup.py
plugins/enhance/enhance.py
plugins/enhance/setup.py
plugins/logstash/logstash.py
plugins/logstash/setup.py
plugins/normalise/normalise.py
plugins/normalise/setup.py
plugins/sns/setup.py
plugins/sns/sns.py

Move some core alerta plugins to contrib

---

plugins/amqp/README

Readme file with basic configuration

Readme for AMQP plugin

---

integrations/consul/consul-alerta.py

Event was statically set to "problem" , which caused different events for the same host to be de-duplicated, instead of creating new ones, events now equals service.

Consul fixed event 

---

integrations/mailer/README.md
integrations/mailer/mailer.py

Some SMTP server must use SSL to connect(Tencent exmail for example), we should add some options to support it.

Add SMTP over SSL support

---

plugins/slack/README.md
plugins/slack/alerta_slack.py

Added configuration variables:
SLACK_CHANNEL, ALERTA_UI_URL, ICON_EMOJI, ALERTA_USERNAME
Also fixes https://github.com/alerta/alerta-contrib/issues/32

Slack plugin update to be more configurable

---

integrations/opsweekly/README.md

Update Opsweekly README

---

integrations/pinger/README.md
integrations/pinger/pinger.py
integrations/pinger/setup.py

Fix alerta pinger and update README

---

plugins/cachet/README.md
plugins/cachet/alerta_cachet.py
plugins/cachet/setup.py

Fix for #105 
Note: Need to add an Incident Template for improved formatting.

Add Cachet incident update plugin

---

integrations/snmptrap/README.md
integrations/snmptrap/handler.py
integrations/snmptrap/setup.py

Use default settins for snmptrapAlert timeout

---

plugins/prometheus/alerta_prometheus.py
plugins/prometheus/setup.py

See guardian/alerta#327 and guardian/alerta#328

Prometheus plugin should use externalUrl if available

---

plugins/influxdb/README.md
plugins/influxdb/alerta_influxdb.py
plugins/influxdb/setup.py

See "Don't have too many series" for more info...
https://docs.influxdata.com/influxdb/v1.2/concepts/schema_and_data_layout/#don-t-have-too-many-series
See #125  /cc @thehilll @jackzampolin

Write alerts to single Influxdb 'event' measurement series only

---

plugins/prometheus/alerta_prometheus.py
plugins/prometheus/setup.py

Prometheus silenceId update to attributes

---

integrations/sqs/alerta_sqs.py

Add new method to custom easily what to do with the sqs message.

Update sqs worker.

---

.gitignore
integrations/mailer/mailer.py
integrations/mailer/requirements.txt
integrations/mailer/setup.py

Update alerta-mailer for v5 API and python 3

---

plugins/amqp/alerta_amqp.py
plugins/amqp/setup.py

Update AMQP plugin for v5

---

integrations/mailer/mailer.py
integrations/mailer/setup.py

Mailer config

---

plugins/zabbix/README.md
plugins/zabbix/alerta_zabbix.py
plugins/zabbix/setup.py

Use Zabbix URL from passed in alert, if available

---

plugins/amqp/alerta_amqp.py
plugins/amqp/listener.py
plugins/amqp/setup.py

Fixes date serializer rather than making dates timezone aware (see #157).

Fix AMQP plugin date serializer

---

plugins/amqp/alerta_amqp.py
plugins/amqp/listener.py
plugins/enhance/setup.py

Amqp get body

---

integrations/consul/consulalerta.py

This PR fixes the following:
* Correct import and usage of `Client` api class
* Ability to configure the consul host/port via ENV variables

Consul fixes

---

plugins/telegram/README.md
plugins/telegram/alerta_telegram.py
plugins/telegram/setup.py

Use jinja2 template as template language.
The probably have to bump not minor version but major one.

use template to send data to tg

---

plugins/pubsub/alerta_pubsub.py

GCP pubsub updated for version 5

---

plugins/pubsub/alerta_pubsub.py
plugins/pubsub/setup.py

GCP pubsub make use of get_body() again

---

integrations/consul/consulalerta.py
integrations/consul/consulheartbeat.py
integrations/consul/setup.py

Update consul integration for v5

---

integrations/mailer/mailer.py
integrations/mailer/setup.py

Update mailer for version 5

---

integrations/pinger/pinger.py
integrations/pinger/setup.py
integrations/snmptrap/handler.py
integrations/snmptrap/setup.py
integrations/supervisor/evlistener.py
integrations/syslog/setup.py
integrations/syslog/syslogfwder.py

Update API client version to 5

---

integrations/snmptrap/README.md
integrations/snmptrap/handler.py
integrations/snmptrap/setup.py

Update SNMP Trap handler for version 5 API

---

plugins/prometheus/alerta_prometheus.py
plugins/prometheus/setup.py

Convert Prometheus Alertmanager silence days to integer

---

plugins/msteams/README.md
plugins/msteams/alerta_msteams.py
plugins/msteams/setup.py

This plugin sends notifications to an MS Teams team room.

Support for sending notifications to MS Teams

---

plugins/logstash/alerta_logstash.py

Fix logstash send for Python 3

---

README.md
plugins/forward/README.md
plugins/forward/alerta_forward.py
plugins/forward/setup.py

sorry , old MR is closed by me.
Sometime is needed send alerts to another alerta instance.

forward plugin (ex-191 MR)

---

webhooks/azuremonitor/README.md
webhooks/azuremonitor/alerta_azuremonitor.py
webhooks/azuremonitor/setup.py

Receive alerts from Azure monitor

Azure monitor webhooks

---

plugins/pubsub/setup.py

Update Google Cloud PubSub dependency

---

plugins/slack/README.md
plugins/slack/alerta_slack.py

- Refactor template expansion logic to be used in several places
- Implement SLACK_PAYLOAD, which allows complete customization of the post payload,
unlocking all Slack API features and providing Jinja2 templating
- The payload support reverts the need for the SLACK_ATTACHMENT_SIZE_MAP.
- Put back the default behavior with SLACK_ATTACHMENTS
- Update doc to show how to use SLACK_PAYLOAD
- Add example use including button to launch alert console

Further work to allow customization of slack payload

---

plugins/influxdb/alerta_influxdb.py
plugins/influxdb/setup.py

Use UTC now() as influxdb timestamp

---

plugins/zabbix/alerta_zabbix.py

Zabbix plugin uses pyzabbix library.
This library doesn't perform user.logout query automatically.
if user.logout is not called, the sessions table of Zabbix DB will be large.  
see:https://github.com/lukecyca/pyzabbix/issues/95

[Zabbix] Add user.logout after api call.

---

plugins/zabbix/alerta_zabbix.py
plugins/zabbix/setup.py

Reduce the number of zabbix logouts

---

plugins/mattermost/README.md
plugins/mattermost/alerta_mattermost.py
plugins/mattermost/setup.py
plugins/telegram/README.md
plugins/telegram/alerta_telegram.py

this PR helps handle telegram proxy in alerta and telepot way (I hope..)
FYI:
https://github.com/nickoala/telepot/issues/309

add http proxy support for telegram plugin, add mattermost plugin

---

plugins/slack/alerta_slack.py

Fix alert payload formatting issue where template text could introduce newlines, which in turn
caused the json.loads() to fail.  The code now properly logs with a traceback any issues
with template formatting, and in DEBUG will print what its doing and what the template
processor spat out.
Note: while we were actually getting some rate-limiting from slack, this was the real culprit for most dropped alerts.

Slack payload formatting error dropped alerts

---

webhooks/azuremonitor/alerta_azuremonitor.py

Some of the grammar was wrong in the comments, corrected.
Improved formatting of code.
Changed 'type' variable to be 'event_type' so as to avoid clashing with the Python inbuilt type function.

Fix formatting, grammar and variable naming

---

.travis.yml
README.md
requirements-dev.txt
webhooks/sentry/alerta_sentry.py
webhooks/sentry/test_sentry.py

Test sentry webhook

---

plugins/forward/alerta_forward.py

fixes the integer conversion problem

fix int conversion

---

webhooks/azuremonitor/alerta_azuremonitor.py

Deactivated is also and recovery status.

Azure monitor status

---

webhooks/azuremonitor/alerta_azuremonitor.py
webhooks/azuremonitor/setup.py

Azure raw data should be string not dict

---

integrations/mailer/mailer.py
integrations/mailer/setup.py

[alerta-mailer] Fix HTML emails

---

plugins/telegram/README.md

Document that telegram plugin TELEGRAM_TEMPLATE can be a filename pointing to Jinja2 template(file).

Document that telegram plugin TELEGRAM_TEMPLATE can be a filename

---

plugins/telegram/README.md
plugins/telegram/alerta_telegram.py
plugins/telegram/setup.py

Enable/disable sound on telegram notifications (uses
disable_notification=False/True from sendMessage telegram api).

telegram: TELEGRAM_SOUND_NOTIFICATION_SEVERITY config option

---

webhooks/sentry/alerta_sentry.py
webhooks/sentry/test_sentry.py

Correct Sentry webhook test and check environment value (#304)
Correct Sentry webhook payload parsing (#304)

Fix Sentry webhook test and payload parsing

---

.gitignore
.pylintrc
.travis.yml
integrations/consul/consulalerta.py
integrations/consul/consulheartbeat.py
integrations/consul/setup.py
integrations/mailer/mailer.py
integrations/urlmon/settings.py
integrations/urlmon/urlmon.py
plugins/alertops/alerta_alertops.py
plugins/mattermost/alerta_mattermost.py
plugins/slack/alerta_slack.py
requirements-dev.txt

Currently pylint will only report on errors.

Run pylint in build pipeline

---

README.md
plugins/msteams/alerta_msteams.py
plugins/msteams/example-payload.json.j2
plugins/msteams/setup.py
webhooks/msteams/README.md
webhooks/msteams/alerta_msteamswebhook.py
webhooks/msteams/setup.py
webhooks/msteams/test_msteamswebhook.py

msteams webhook implementation. (This was briefly discussed in https://github.com/alerta/alerta-contrib/issues/280)

Msteams webhook

---

integrations/mailer/README.md
integrations/mailer/mailer.py

allow integration user to pick what sevs they want email for.

Pickable sevs

---

plugins/telegram/README.md
plugins/telegram/alerta_telegram.py

I have modified the Telegram plugin to specify multiple chat_ids

Added possibility to specify multiple chat_ids

---

plugins/twilio/setup.py

See https://github.com/twilio/twilio-python/issues/556

build(deps): use twilio pkg that does not pin PyJWT version

---

README.md
plugins/matrix/README.md
plugins/matrix/alerta_matrix.py
plugins/matrix/setup.py

This is a plugin for sending notifications via Matrix.

Add plugin for Matrix notifications

---

integrations/mailer/mailer.py

Add regex check before adding as a valid mailer rules.

Add regex check to mailer rules

---

plugins/prometheus/alerta_prometheus.py

Prometheus Ack timeout from alert not action
